export const actions = {
  post: {
    DATA_FETCHING: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
    DATA_CREATED: "POST_DATA_CREATED",
    DATA_EDITED: "POST_DATA_EDITED",
    POST_DELETED: "POST_DATA_DELETED",
    POST_LIKED: "POST_LIKED",
  },
  comment: {
    COMMENT_FETCHING: "POST_COMMENT_FETCHING",
    POST_COMMENTED: "POST_COMMENTED",
    POST_COMMENT_CREATED: "POST_COMMENT_CREATED",
    COMMENT_FETCH_ERROR: "COMMENT_FETCH_ERROR",
  },
};
