export const actions = {
  post: {
    DATA_FETCHING: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
    DATA_CREATED: "POST_DATA_CREATED",
    DATA_EDITED: "POST_DATA_EDITED",
    POST_DELETED: "POST_DATA_DELETED",
    POST_LIKED: "POST_LIKED",
    POST_SHARED: "POST_SHARED",
  },
  comment: {
    COMMENT_FETCHING: "POST_COMMENT_FETCHING",
    POST_COMMENTED: "POST_COMMENTED",
    POST_COMMENT_CREATED: "POST_COMMENT_CREATED",
    COMMENT_FETCH_ERROR: "COMMENT_FETCH_ERROR",
  },
  story: {
    STORY_FETCHING: "STORY_FETCHING",
    STORY_FETCHED: "STORY_FETCHED",
    STORY_CREATED: "STORY_CREATED",
    STORY_FETCHED_ERROR: "STORY_FETCHED_ERROR",
  },
  profile: {
    USER_PROFILE_FETCHING: "PROFILE_FETCHING",
    USER_PROFILE_FETCHED: "PROFILE_FETCHED",
    USER_PROFILE_EDITED: "PROFILE_EDITED",
    USER_PROFILE_FETCHED_ERROR: "PROFILE_FETCHED_ERROR",
  },
};
